name: Build PDF
on:
  push:
    paths:
      - "**.tex"
      - "**.bib"
      - "latexmkrc"
      - ".github/workflows/latex.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # latexmk w kontenerze texlive-full odpali biber + makeglossaries wg latexmkrc
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -file-line-error -halt-on-error

      - uses: actions/upload-artifact@v4
        with:
          name: document
          path: main.pdf
