name: Build PDF
on:
  push:
    paths:
      - "**.tex"
      - "**.bib"
      - "latexmkrc"
      - ".github/workflows/latex.yml"
  workflow_dispatch: {}   # przycisk "Run workflow" w Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Pierwszy przebieg LaTeX (powstaje .bcf)
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -file-line-error -halt-on-error

      # 2. BibLaTeX + Glossaries
      - run: biber main
      - run: makeglossaries main

      # 3. Dwa kolejne przebiegi LaTeX
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -file-line-error -halt-on-error
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -file-line-error -halt-on-error

      # 4. Artefakt z PDF
      - uses: actions/upload-artifact@v4
        with:
          name: document
          path: main.pdf
